// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace surveyFormUiTest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - Use 'RecordedMethod1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinWindow uITitleGoogleChromeWindow1 = this.UITitleGoogleChromeWindow.UITitleGoogleChromeWindow1;
            WinControl uIChromeLegacyWindowDocument = this.UITitleGoogleChromeWindow.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            #endregion

            // Click 'Title - Google Chrome' window
            Mouse.Click(uITitleGoogleChromeWindow1, new Point(293, 292));

            // Type '{NumPad1}{NumPad0}{NumPad7}{NumPad6}' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.RecordedMethod1Params.UIChromeLegacyWindowDocumentSendKeys, ModifierKeys.None);

            // Click 'Title - Google Chrome' window
            Mouse.Click(uITitleGoogleChromeWindow1, new Point(477, 297));

            // Type 'Control, Shift + f' in 'Chrome Legacy Window' document
            Keyboard.SendKeys(uIChromeLegacyWindowDocument, this.RecordedMethod1Params.UIChromeLegacyWindowDocumentSendKeys1, (ModifierKeys.Control | ModifierKeys.Shift));

            // Click 'Title - Google Chrome' window
            Mouse.Click(uITitleGoogleChromeWindow1, new Point(136, 730));
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UITitleGoogleChromeWindow UITitleGoogleChromeWindow
        {
            get
            {
                if ((this.mUITitleGoogleChromeWindow == null))
                {
                    this.mUITitleGoogleChromeWindow = new UITitleGoogleChromeWindow();
                }
                return this.mUITitleGoogleChromeWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UITitleGoogleChromeWindow mUITitleGoogleChromeWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '{NumPad1}{NumPad0}{NumPad7}{NumPad6}' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys = "{NumPad1}{NumPad0}{NumPad7}{NumPad6}";
        
        /// <summary>
        /// Type 'Control, Shift + f' in 'Chrome Legacy Window' document
        /// </summary>
        public string UIChromeLegacyWindowDocumentSendKeys1 = "f";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITitleGoogleChromeWindow : WinWindow
    {
        
        public UITitleGoogleChromeWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Title - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("Title - Google Chrome");
            this.WindowTitles.Add("localhost:3499/surveys/Survey_12BB1374A9E04977AB04C99E2BC1DA59.aspx?hash=1076 - G" +
                    "oogle Chrome");
            #endregion
        }
        
        #region Properties
        public WinWindow UITitleGoogleChromeWindow1
        {
            get
            {
                if ((this.mUITitleGoogleChromeWindow1 == null))
                {
                    this.mUITitleGoogleChromeWindow1 = new WinWindow(this);
                    #region Search Criteria
                    this.mUITitleGoogleChromeWindow1.SearchProperties[WinWindow.PropertyNames.Name] = "Title";
                    this.mUITitleGoogleChromeWindow1.WindowTitles.Add("Title - Google Chrome");
                    this.mUITitleGoogleChromeWindow1.WindowTitles.Add("localhost:3499/surveys/Survey_12BB1374A9E04977AB04C99E2BC1DA59.aspx?hash=1076 - G" +
                            "oogle Chrome");
                    #endregion
                }
                return this.mUITitleGoogleChromeWindow1;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITitleGoogleChromeWindow1;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "732622712";
            this.WindowTitles.Add("Title - Google Chrome");
            this.WindowTitles.Add("localhost:3499/surveys/Survey_12BB1374A9E04977AB04C99E2BC1DA59.aspx?hash=1076 - G" +
                    "oogle Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region Search Criteria
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("Title - Google Chrome");
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("localhost:3499/surveys/Survey_12BB1374A9E04977AB04C99E2BC1DA59.aspx?hash=1076 - G" +
                            "oogle Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
}
